#!/usr/bin/env bash
# tools/setup-hotspot.sh — bring up (or refresh) the r2-workshop WiFi AP
# on the USB adapter, using the credentials currently in
# firmware/esp32-s3/wifi_config.toml.
#
# This is the temporary stand-in for Phase 6's BLE-bootstrap auto-flow:
# the firmware learns SSID/PSK from wifi_config.toml at compile time
# rather than over BLE. Once Phase 6 lands, this script retires.
#
# Re-running is safe — the existing NetworkManager profile is removed
# first. To regenerate fresh credentials, re-run with `--rotate`.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WIFI_CFG="${REPO_ROOT}/firmware/esp32-s3/wifi_config.toml"
PROFILE="r2-workshop-ap"
IFACE_DEFAULT="wlx0c0e766e358c"

# Pick interface — let CLI override.
IFACE="${R2_HOTSPOT_IFACE:-${IFACE_DEFAULT}}"

ROTATE=0
for arg in "$@"; do
    case "$arg" in
        --rotate) ROTATE=1 ;;
        --iface=*) IFACE="${arg#--iface=}" ;;
        --help|-h)
            cat <<HELP
Usage: $(basename "$0") [--rotate] [--iface=<name>]

  --rotate          Generate fresh SSID/PSK before bringing the AP up.
                    Otherwise reuse what's already in wifi_config.toml.
  --iface=<name>    WiFi interface for the hotspot
                    (default: ${IFACE_DEFAULT}, env: R2_HOTSPOT_IFACE).

Reads / writes:  firmware/esp32-s3/wifi_config.toml
HELP
            exit 0
            ;;
    esac
done

if ! command -v nmcli >/dev/null 2>&1; then
    echo "FATAL: nmcli not found — NetworkManager required." >&2
    exit 1
fi

if ! nmcli -t -f DEVICE device | grep -q "^${IFACE}\$"; then
    echo "FATAL: interface ${IFACE} not present." >&2
    echo "       Available interfaces:" >&2
    nmcli -t -f DEVICE,TYPE device | awk -F: '$2=="wifi"{print "         " $1}' >&2
    exit 1
fi

# Generate fresh credentials if --rotate or wifi_config.toml is missing.
if (( ROTATE )) || [[ ! -f "${WIFI_CFG}" ]]; then
    SSID="r2-workshop-$(head -c 3 /dev/urandom | hexdump -e '/1 "%02x"')"
    PSK=$(head -c 18 /dev/urandom | base64 | tr -d '/+=' | head -c 20)
    cat > "${WIFI_CFG}" <<TOML
# r2-workshop test credentials. Auto-generated by tools/setup-hotspot.sh.
# Gitignored. Re-run setup-hotspot.sh --rotate to regenerate.

ssid       = "${SSID}"
password   = "${PSK}"
gateway_ip = "10.42.0.1"
TOML
    echo "Wrote fresh credentials to ${WIFI_CFG}"
else
    SSID=$(awk -F'"' '$1=="ssid       = " || $1=="ssid = "    {print $2}' "${WIFI_CFG}")
    PSK=$( awk -F'"' '$1=="password   = " || $1=="password = "{print $2}' "${WIFI_CFG}")
    if [[ -z "${SSID}" || -z "${PSK}" ]]; then
        echo "FATAL: could not parse ssid/password from ${WIFI_CFG}." >&2
        echo "       Run with --rotate to regenerate, or fix the file by hand." >&2
        exit 1
    fi
    echo "Reusing credentials from ${WIFI_CFG}"
fi

echo "  ssid:       ${SSID}"
echo "  password:   ${PSK}"
echo "  iface:      ${IFACE}"
echo "  gateway:    10.42.0.1 (NetworkManager 'shared' default)"
echo

# Tear down any prior r2-workshop-ap profile.
if nmcli -t -f NAME connection show | grep -q "^${PROFILE}\$"; then
    echo "Removing prior ${PROFILE} profile…"
    nmcli connection down "${PROFILE}" 2>/dev/null || true
    nmcli connection delete "${PROFILE}"
fi

# Disconnect the chosen interface from any active WiFi.
echo "Disconnecting ${IFACE} from any current network…"
nmcli device disconnect "${IFACE}" 2>/dev/null || true

# Create the AP profile.
echo "Creating ${PROFILE} profile…"
nmcli connection add \
    type wifi \
    ifname "${IFACE}" \
    con-name "${PROFILE}" \
    autoconnect no \
    ssid "${SSID}" \
    >/dev/null

nmcli connection modify "${PROFILE}" \
    802-11-wireless.mode ap \
    802-11-wireless.band bg \
    ipv4.method shared \
    ipv6.method ignore \
    wifi-sec.key-mgmt wpa-psk \
    wifi-sec.psk "${PSK}"

echo "Bringing ${PROFILE} up…"
nmcli connection up "${PROFILE}"

echo
echo "Hotspot is up. Confirm with:"
echo "    nmcli device wifi list ifname ${IFACE}"
echo "    ip -4 addr show ${IFACE}"
echo
echo "Next:"
echo "  1. cd firmware/esp32-s3 && source ~/export-esp.sh && cargo build --release"
echo "     (build.rs picks up the new wifi_config.toml)"
echo "  2. espflash flash --port /dev/ttyUSB0 \\"
echo "       target/xtensa-esp32s3-espidf/release/r2-workshop-firmware"
echo "  3. cd ../.. && cargo run --release -p r2-dashboard"
echo "  4. Open http://localhost:8080 in a browser."
